name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  style_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: style_check_maven
      - name: Check Format
        run: ./mvnw editorconfig:check

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: build_maven
      - name: Build
        run: ./mvnw install -e
      - name: Upload generated sources
        uses: actions/upload-artifact@v4
        with:
          name: generated-sources
          path: |
            ./it/java8/target/generated-sources
            ./it/java17/target/generated-sources
          if-no-files-found: error
          retention-days: 3
      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
              ~/.m2/repository/online/sharedtype
          if-no-files-found: error
          retention-days: 3
      - name: Remove jars from cache
        run: rm -rf ~/.m2/repository/online/sharedtype

  jdk_compatibility_test:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/download-artifact@v4
        with:
          name: jars
          path: ~/.m2/repository/online/sharedtype
#      - name: Display downloaded artifact
#        run: ls -lhR ~/.m2/repository/online/sharedtype
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: build_maven
      - name: Test
        run: ./mvnw verify -pl it/java8 -e

  client_test:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/download-artifact@v4
        with:
          name: generated-sources
          path: ./it/
#      - name: Display downloaded artifact
#        run: ls -lhR ./it/
      - name: Test Typescript
        working-directory: client-test/typescript
        run: |
          npm i
          npm run test

#  clean-artifact:
#    needs: [ jdk_compatibility_test, client_test ]
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      - uses: geekyeggo/delete-artifact@v5
#        with:
#          name: dist
